// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.3
// source: perform.proto

package perform_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_RUNNING Status = 0 // 运行中
	Status_STATUS_IDLE    Status = 1 // 空闲
	Status_STATUS_ERROR   Status = 2 // 异常
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_RUNNING",
		1: "STATUS_IDLE",
		2: "STATUS_ERROR",
	}
	Status_value = map[string]int32{
		"STATUS_RUNNING": 0,
		"STATUS_IDLE":    1,
		"STATUS_ERROR":   2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_perform_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_perform_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_perform_proto_rawDescGZIP(), []int{0}
}

type StartMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          []byte                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartMessage) Reset() {
	*x = StartMessage{}
	mi := &file_perform_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMessage) ProtoMessage() {}

func (x *StartMessage) ProtoReflect() protoreflect.Message {
	mi := &file_perform_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMessage.ProtoReflect.Descriptor instead.
func (*StartMessage) Descriptor() ([]byte, []int) {
	return file_perform_proto_rawDescGZIP(), []int{0}
}

func (x *StartMessage) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

type ExecutorStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=perform.Status" json:"status,omitempty"` // 使用枚举类型表示状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutorStatus) Reset() {
	*x = ExecutorStatus{}
	mi := &file_perform_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutorStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutorStatus) ProtoMessage() {}

func (x *ExecutorStatus) ProtoReflect() protoreflect.Message {
	mi := &file_perform_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutorStatus.ProtoReflect.Descriptor instead.
func (*ExecutorStatus) Descriptor() ([]byte, []int) {
	return file_perform_proto_rawDescGZIP(), []int{1}
}

func (x *ExecutorStatus) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_RUNNING
}


type CmRespMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       []byte                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmRespMessage) Reset() {
	*x = CmRespMessage{}
	mi := &file_perform_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmRespMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmRespMessage) ProtoMessage() {}

func (x *CmRespMessage) ProtoReflect() protoreflect.Message {
	mi := &file_perform_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmRespMessage.ProtoReflect.Descriptor instead.
func (*CmRespMessage) Descriptor() ([]byte, []int) {
	return file_perform_proto_rawDescGZIP(), []int{2}
}

func (x *CmRespMessage) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CmRespMessage) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type EmptyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	mi := &file_perform_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_perform_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMessage.ProtoReflect.Descriptor instead.
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return file_perform_proto_rawDescGZIP(), []int{3}
}

type PerformMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Stats         *PerformStats          `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerformMessage) Reset() {
	*x = PerformMessage{}
	mi := &file_perform_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformMessage) ProtoMessage() {}

func (x *PerformMessage) ProtoReflect() protoreflect.Message {
	mi := &file_perform_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformMessage.ProtoReflect.Descriptor instead.
func (*PerformMessage) Descriptor() ([]byte, []int) {
	return file_perform_proto_rawDescGZIP(), []int{4}
}

func (x *PerformMessage) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PerformMessage) GetStats() *PerformStats {
	if x != nil {
		return x.Stats
	}
	return nil
}


type PerformStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrCount      int64                  `protobuf:"varint,1,opt,name=err_count,json=errCount,proto3" json:"err_count,omitempty"`
	SendCount     int64                  `protobuf:"varint,2,opt,name=send_count,json=sendCount,proto3" json:"send_count,omitempty"`
	SendBytes     int64                  `protobuf:"varint,3,opt,name=send_bytes,json=sendBytes,proto3" json:"send_bytes,omitempty"`
	RecvBytes     int64                  `protobuf:"varint,4,opt,name=recv_bytes,json=recvBytes,proto3" json:"recv_bytes,omitempty"`
	Duration      int64                  `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"`
	Latency       []*Record              `protobuf:"bytes,6,rep,name=latency,proto3" json:"latency,omitempty"`
	ErrMsgs       [][]byte               `protobuf:"bytes,7,rep,name=err_msgs,json=errMsgs,proto3" json:"err_msgs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerformStats) Reset() {
	*x = PerformStats{}
	mi := &file_perform_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformStats) ProtoMessage() {}

func (x *PerformStats) ProtoReflect() protoreflect.Message {
	mi := &file_perform_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformStats.ProtoReflect.Descriptor instead.
func (*PerformStats) Descriptor() ([]byte, []int) {
	return file_perform_proto_rawDescGZIP(), []int{5}
}

func (x *PerformStats) GetErrCount() int64 {
	if x != nil {
		return x.ErrCount
	}
	return 0
}

func (x *PerformStats) GetSendCount() int64 {
	if x != nil {
		return x.SendCount
	}
	return 0
}

func (x *PerformStats) GetSendBytes() int64 {
	if x != nil {
		return x.SendBytes
	}
	return 0
}

func (x *PerformStats) GetRecvBytes() int64 {
	if x != nil {
		return x.RecvBytes
	}
	return 0
}

func (x *PerformStats) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *PerformStats) GetLatency() []*Record {
	if x != nil {
		return x.Latency
	}
	return nil
}

func (x *PerformStats) GetErrMsgs() [][]byte {
	if x != nil {
		return x.ErrMsgs
	}
	return nil
}

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           int64                  `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_perform_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_perform_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_perform_proto_rawDescGZIP(), []int{6}
}

func (x *Record) GetKey() int64 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *Record) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_perform_proto protoreflect.FileDescriptor

var file_perform_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x70, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x22, 0x22, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6a, 0x73, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x22, 0x39, 0x0a, 0x0e,
	0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x27,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f,
	0x2e, 0x70, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x3d, 0x0a, 0x0d, 0x43, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x0e, 0x0a, 0x0c, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x51, 0x0a, 0x0e, 0x50, 0x65, 0x72, 0x66, 0x6f, 0x72,
	0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x2b, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x65,
	0x72, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x50, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x53, 0x74, 0x61,
	0x74, 0x73, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x22, 0xea, 0x01, 0x0a, 0x0c, 0x50, 0x65,
	0x72, 0x66, 0x6f, 0x72, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x72,
	0x72, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x65,
	0x72, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x5f,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x65, 0x6e,
	0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x62,
	0x79, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x65, 0x6e, 0x64,
	0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x63, 0x76, 0x5f, 0x62, 0x79,
	0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x72, 0x65, 0x63, 0x76, 0x42,
	0x79, 0x74, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x29, 0x0a, 0x07, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x06, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x52, 0x07, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x65,
	0x72, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x07, 0x65,
	0x72, 0x72, 0x4d, 0x73, 0x67, 0x73, 0x22, 0x30, 0x0a, 0x06, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2a, 0x3f, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x52, 0x55, 0x4e,
	0x4e, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x5f, 0x49, 0x44, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x54, 0x41, 0x54, 0x55,
	0x53, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x02, 0x32, 0x8b, 0x02, 0x0a, 0x0e, 0x50, 0x65,
	0x72, 0x66, 0x6f, 0x72, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x0c,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x15, 0x2e, 0x70,
	0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x1a, 0x16, 0x2e, 0x70, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x43, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3d, 0x0a, 0x0b, 0x53,
	0x74, 0x6f, 0x70, 0x50, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x15, 0x2e, 0x70, 0x65, 0x72,
	0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x1a, 0x17, 0x2e, 0x70, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x50, 0x65, 0x72, 0x66,
	0x6f, 0x72, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3e, 0x0a, 0x0c, 0x43, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x15, 0x2e, 0x70, 0x65, 0x72,
	0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x1a, 0x17, 0x2e, 0x70, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x50, 0x65, 0x72, 0x66,
	0x6f, 0x72, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3b, 0x0a, 0x09, 0x4b, 0x65,
	0x65, 0x70, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x12, 0x15, 0x2e, 0x70, 0x65, 0x72, 0x66, 0x6f, 0x72,
	0x6d, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x17,
	0x2e, 0x70, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x13, 0x5a, 0x11, 0x73, 0x72, 0x63, 0x2f, 0x70,
	0x62, 0x3b, 0x70, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_perform_proto_rawDescOnce sync.Once
	file_perform_proto_rawDescData = file_perform_proto_rawDesc
)

func file_perform_proto_rawDescGZIP() []byte {
	file_perform_proto_rawDescOnce.Do(func() {
		file_perform_proto_rawDescData = protoimpl.X.CompressGZIP(file_perform_proto_rawDescData)
	})
	return file_perform_proto_rawDescData
}

var file_perform_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_perform_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_perform_proto_goTypes = []any{
	(Status)(0),            // 0: perform.Status
	(*StartMessage)(nil),   // 1: perform.StartMessage
	(*ExecutorStatus)(nil), // 2: perform.ExecutorStatus
	(*CmRespMessage)(nil),  // 3: perform.CmRespMessage
	(*EmptyMessage)(nil),   // 4: perform.EmptyMessage
	(*PerformMessage)(nil), // 5: perform.PerformMessage
	(*PerformStats)(nil),   // 6: perform.PerformStats
	(*Record)(nil),         // 7: perform.Record
}
var file_perform_proto_depIdxs = []int32{
	0, // 0: perform.ExecutorStatus.status:type_name -> perform.Status
	6, // 1: perform.PerformMessage.stats:type_name -> perform.PerformStats
	7, // 2: perform.PerformStats.latency:type_name -> perform.Record
	1, // 3: perform.PerformService.StartPerform:input_type -> perform.StartMessage
	4, // 4: perform.PerformService.StopPerform:input_type -> perform.EmptyMessage
	4, // 5: perform.PerformService.CollectStats:input_type -> perform.EmptyMessage
	4, // 6: perform.PerformService.KeepAlive:input_type -> perform.EmptyMessage
	3, // 7: perform.PerformService.StartPerform:output_type -> perform.CmRespMessage
	5, // 8: perform.PerformService.StopPerform:output_type -> perform.PerformMessage
	5, // 9: perform.PerformService.CollectStats:output_type -> perform.PerformMessage
	2, // 10: perform.PerformService.KeepAlive:output_type -> perform.ExecutorStatus
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_perform_proto_init() }
func file_perform_proto_init() {
	if File_perform_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_perform_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_perform_proto_goTypes,
		DependencyIndexes: file_perform_proto_depIdxs,
		EnumInfos:         file_perform_proto_enumTypes,
		MessageInfos:      file_perform_proto_msgTypes,
	}.Build()
	File_perform_proto = out.File
	file_perform_proto_rawDesc = nil
	file_perform_proto_goTypes = nil
	file_perform_proto_depIdxs = nil
}