// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: perform.proto

package perform_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PerformService_StartPerform_FullMethodName = "/perform.PerformService/StartPerform"
	PerformService_StopPerform_FullMethodName  = "/perform.PerformService/StopPerform"
	PerformService_CollectStats_FullMethodName = "/perform.PerformService/CollectStats"
	PerformService_KeepAlive_FullMethodName    = "/perform.PerformService/KeepAlive"
)

// PerformServiceClient is the client API for PerformService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PerformServiceClient interface {
	StartPerform(ctx context.Context, in *StartMessage, opts ...grpc.CallOption) (*CmRespMessage, error)
	StopPerform(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*PerformMessage, error)
	CollectStats(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*PerformMessage, error)
	KeepAlive(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*ExecutorStatus, error)
}

type performServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPerformServiceClient(cc grpc.ClientConnInterface) PerformServiceClient {
	return &performServiceClient{cc}
}

func (c *performServiceClient) StartPerform(ctx context.Context, in *StartMessage, opts ...grpc.CallOption) (*CmRespMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CmRespMessage)
	err := c.cc.Invoke(ctx, PerformService_StartPerform_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *performServiceClient) StopPerform(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*PerformMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PerformMessage)
	err := c.cc.Invoke(ctx, PerformService_StopPerform_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *performServiceClient) CollectStats(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*PerformMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PerformMessage)
	err := c.cc.Invoke(ctx, PerformService_CollectStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *performServiceClient) KeepAlive(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*ExecutorStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutorStatus)
	err := c.cc.Invoke(ctx, PerformService_KeepAlive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PerformServiceServer is the server API for PerformService service.
// All implementations must embed UnimplementedPerformServiceServer
// for forward compatibility.
type PerformServiceServer interface {
	StartPerform(context.Context, *StartMessage) (*CmRespMessage, error)
	StopPerform(context.Context, *EmptyMessage) (*PerformMessage, error)
	CollectStats(context.Context, *EmptyMessage) (*PerformMessage, error)
	KeepAlive(context.Context, *EmptyMessage) (*ExecutorStatus, error)
	mustEmbedUnimplementedPerformServiceServer()
}

// UnimplementedPerformServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPerformServiceServer struct{}

func (UnimplementedPerformServiceServer) StartPerform(context.Context, *StartMessage) (*CmRespMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartPerform not implemented")
}
func (UnimplementedPerformServiceServer) StopPerform(context.Context, *EmptyMessage) (*PerformMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopPerform not implemented")
}
func (UnimplementedPerformServiceServer) CollectStats(context.Context, *EmptyMessage) (*PerformMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CollectStats not implemented")
}
func (UnimplementedPerformServiceServer) KeepAlive(context.Context, *EmptyMessage) (*ExecutorStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KeepAlive not implemented")
}
func (UnimplementedPerformServiceServer) mustEmbedUnimplementedPerformServiceServer() {}
func (UnimplementedPerformServiceServer) testEmbeddedByValue()                        {}

// UnsafePerformServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PerformServiceServer will
// result in compilation errors.
type UnsafePerformServiceServer interface {
	mustEmbedUnimplementedPerformServiceServer()
}

func RegisterPerformServiceServer(s grpc.ServiceRegistrar, srv PerformServiceServer) {
	// If the following call pancis, it indicates UnimplementedPerformServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PerformService_ServiceDesc, srv)
}

func _PerformService_StartPerform_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerformServiceServer).StartPerform(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PerformService_StartPerform_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerformServiceServer).StartPerform(ctx, req.(*StartMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _PerformService_StopPerform_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerformServiceServer).StopPerform(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PerformService_StopPerform_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerformServiceServer).StopPerform(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _PerformService_CollectStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerformServiceServer).CollectStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PerformService_CollectStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerformServiceServer).CollectStats(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _PerformService_KeepAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerformServiceServer).KeepAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PerformService_KeepAlive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerformServiceServer).KeepAlive(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// PerformService_ServiceDesc is the grpc.ServiceDesc for PerformService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PerformService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "perform.PerformService",
	HandlerType: (*PerformServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartPerform",
			Handler:    _PerformService_StartPerform_Handler,
		},
		{
			MethodName: "StopPerform",
			Handler:    _PerformService_StopPerform_Handler,
		},
		{
			MethodName: "CollectStats",
			Handler:    _PerformService_CollectStats_Handler,
		},
		{
			MethodName: "KeepAlive",
			Handler:    _PerformService_KeepAlive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "perform.proto",
}
